config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'reviews/create'
  get 'reviews/destroy'

  get 'products/index'
  get 'products/new'
  get 'products/create'
  get 'products/show'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'

  get 'profile', to: 'users#show', as: :user_profile

  post 'update_product', to: 'carts#update_product', as: :update_product
  delete 'remove', to: 'carts#remove', as: :remove_product

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products do
    resources :reviews, only: :create
  end
  resources :users
  resources :reviews, only: :destroy

  resources :carts, only: [:show]
  resources :cart_products, only: [:create, :destroy]

  resources :orders, only: [:create, :show, :index]
  resources :order_products, only: [:create, :destroy]


end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart
    @cart_products = @cart.cart_products.includes(:product)
    @total_due = calculate_total_due(@cart_products)
  end

  def update_product
    cart = current_user.cart
    cart_product = cart.cart_products.find_by(product_id: params[:product_id])
  end


  def remove
  end

  private

  def calculate_total_due(cart_products)
    cart_products.sum { |cart_product| cart_product.quantity * cart_product.price }
  end
end

app/views/carts/add_item.html.erb
<h1>Cart#add_item</h1>
<p>Find me in app/views/cart/add_item.html.erb</p>

app/views/carts/remove_item.html.erb
<h1>Cart#remove_item</h1>
<p>Find me in app/views/cart/remove_item.html.erb</p>

app/views/carts/show.html.erb
<div class="container">
    <%= link_to "Back", products_index_path, class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="container mt-4 ">
  <div class="row d-flex justify-content-center mt-3 rounded-2">
    <h1 class="h1-cart text-center" style="text-shadow: 1px 1px 1px #000000;">Shopping cart</h1>
  </div>
  <div class="container mt-4 ">
    <h4 class="product-list-title">Products list</h2>
  </div>
  <div class="container mt-3">
    <% @cart_products.each do |cart_product| %>
      <div class="card mb-3 card-hover shadow p-3 mb-5">
        <div class="row g-0">
          <div class="col-md-4 r">
            <% if cart_product.product.photo.attached? %>
              <%= image_tag cart_product.product.photo, class: 'product-image', height: 200, width: 300, crop: :fill  %>
            <% else %>
              <p>No image available</p>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= cart_product.product.title %></h5>
              <p class="product-description"><%= cart_product.product.description %></p>
              <p class="card-text">
                <small class="text-muted">Part number: <%= cart_product.product.id %></small>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <label class="text-muted">Precio:</label>
                  <span class="text-muted"><%= number_to_currency(cart_product.price) %></span>
                </div>
                <div>
                  <label class="text-muted">Total:</label>
                  <span class="text-muted"><%= number_to_currency(cart_product.quantity * cart_product.price) %></span>
                </div>
                <div>
                  <label for="quantity-<%= cart_product.id %>" class="text-muted">Cantidad:</label>
                  <input id="quantity-<%= cart_product.id %>" class="form-control quantity-input" type="number" value="<%= cart_product.quantity %>" min="0" name="product_quantity">
                </div>
                <div>
                  <%= button_to 'Update', update_product_path(product_id: cart_product.product.id), class: "btn btn-outline-secondary btn-sm" %>
                  <%= link_to 'Remove', "#", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-end">
    <div class="text-end">
      <h3 class="product-total-title">Total: <%= number_to_currency(@total_due) %></h3>
      <%= button_to 'Place Order', orders_path, class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
</div>