config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'reviews/create'
  get 'reviews/destroy'

  get 'products/index'
  get 'products/new'
  get 'products/create'
  get 'products/show'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'

  get 'profile', to: 'users#show', as: :user_profile

  post 'update_product', to: 'carts#update_product', as: :update_product
  delete 'remove', to: 'carts#remove', as: :remove_product

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products do
    resources :reviews, only: :create
  end
  resources :users
  resources :reviews, only: :destroy

  resources :carts, only: [:show]
  resources :cart_products, only: [:create, :destroy]

  resources :orders, only: [:create, :show, :index]
  resources :order_products, only: [:create, :destroy]


end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  price       :float
#  quantity    :integer
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  belongs_to :user

  has_one_attached :photo
  validates :title, uniqueness: true, presence: true
  validates :description, :quantity, :price, :photo, presence: true
  validates :description, length: {minimum: 6}

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [ :title, :description ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: [ :index, :show, :edit, :destroy ]
  # skip_before_action :authenticate_user!, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]

  def index
    @products = Product.all
    if params[:query].present?
      @products = @products.search_by_title_and_description(params[:query])
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @review = Review.new(product: @product)
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :photo)
  end
end

app/views/products/_form.html.erb
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-12 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3>Create a new product</h3>
          <%= simple_form_for @product do |f| %>
            <%= f.input :title, placeholder: 'Product' %>
            <%= f.input :description, placeholder: "Add your description here..." %>
            <%= f.input :quantity, placeholder: 1 %>
            <%= f.input :price, placeholder: 1 %>
            <%= f.input :photo, as: :file, required: true %>
            <%= f.submit class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container d-flex justify-content-start my-4">
      <%= link_to "Return to products", products_path%>
  </div>

app/views/products/_product.html.erb
<%= product.title %>
<%=  cl_image_tag product.photo.key %>

app/views/products/edit.html.erb
  <div class="container mt-4">
    <div class="row d-flex justify-content-center">
      <div class="col-6 m-auto">
        <div>
          <h1 d-flex justify-content-center>Edit a Product</h1>
          <div class="mt-3">
            <%= render "form", product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
<div class="container mt-3 position-relative">
  <div class="row">
    <div class="col-12">
       <h1 class="title-card">
        Find the pet product you want
        <i class="fas fa-heart" style="font-size: 25px"></i>
      </h1>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @products.count %> products out of our <%= Product.count %> on our website.</p>
      <% else %>
        <p>All <%= Product.count %> products.</p>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <% if user_signed_in? %>
    <h3>Create a Product</h3>
    <%= link_to "Add a Product", new_product_path, class: "btn btn-primary rounded mb-3" %>
  <% end %>
</div>

<div class="container">
    <%= link_to "Return Home", root_path, class: "btn btn-outline-secondary btn-sm" %>
</div>

<div class="container">
  <div class="row d-flex justify-content-center mt-3">
    <% @products.each do |product| %>
      <div class="col-3 mx-3 my-3 shadow p-3 mb-5 rounded card-hover d-flex flex-column">
        <div class="flex-grow-1">
          <div class="d-flex justify-content-center ms-3">
            <% if product.photo.present? && product.photo.key.present? %>
              <%= cl_image_tag product.photo.key, class: 'product-image', height: 200, width: 200, crop: :fill %>
            <% end %>
          </div>
          <div class="d-flex justify-content-center mt-3">
            <h5><%= product.title %></h5>
          </div>
          <div class="d-flex justify-content-center">
            <p class="product-description"><%= product.description %></p>
          </div>
          <div class="d-flex justify-content-center">
            <div class="d-flex pe-4 align-items-center">
              <h6 class="me-2 mb-0">Quantity:</h6>
              <span><%= product.quantity %></span>
            </div>
            <div class="d-flex align-items-center">
              <h6 class="me-2 mb-0">Price:</h6>
              <i class="fa-solid fa-dollar-sign"></i>
              <span><%= product.price %></span>
            </div>
          </div>
        </div>
        <div class="mt-auto d-flex justify-content-center">
          <%= link_to "More info", product_path(product), class: "btn btn-primary rounded mb-3" %>
            <%#= link_to "Add to cart", cart_products_path(@product), class: "btn btn-danger text-white"%>
          <% if user_signed_in? %>
            <% if current_user.id != product.user_id %>
              <form action="/cart_products" method="POST" data-turbo="false">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <%= hidden_field_tag :product_id, product.id %>
                <input type="submit" value="Add to cart", class= "btn btn-danger text-white">
              </form>
            <% end  %>
          <% else %>
            <%= link_to "Sign in to Add to Cart", new_user_session_path, class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="mt-auto d-flex justify-content-center">
          <% if product.user == current_user %>
            <%= link_to "Edit", edit_product_path(product), class: "btn btn-secondary text-light rounded mb-3" %>
            <%= link_to "Remove", product_path(product),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-danger text-light rounded mb-3" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="bg-white text-dark" data-dark-target="html">
  <div class="container mt-4 ">
    <div class="row d-flex justify-content-center">
      <div class="col-6 m-auto">
        <div>
          <h1 class="d-flex justify-content-center">Add a new Product</h1>
          <div class="mt-3">
            <%= render "form", product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">

  <div class="container my-2">
      <div>
          <div class="flex">
            <div class="d-flex justify-content-start mt-3">
              <h4 ><%= @product.title %></h4>
            </div>
            <div class="d-flex justify-content-start ms-3">
              <%if @product.photo.attached? %>
                <%= cl_image_tag @product.photo.key, class: 'product-image', height: 200, width: 200, crop: :fill  %>
              <%else  %>
                <%=image_tag "imgnotavailable.png"  %>
              <%end %>
            </div>
            <div class="d-flex justify-content-start">
              <p class="product-description"><%= @product.description %></p>
            </div>
            <div class="d-flex justify-content-start">
              <div class="d-flex pe-4 align-items-center">
                <h6 class="me-2 mb-0">Quantity:</h6>
                <span><%= @product.quantity %></span>
              </div>
              <div class="d-flex align-items-center">
                <h6 class="me-2 mb-0">Price:</h6>
                <i class="fa-solid fa-dollar-sign"></i>
                <span><%= @product.price %></span>
              </div>
            </div>
          </div>
      </div>
      <div class="d-flex justify-content-between my-3">
          <div>
            <%#= link_to "Add to cart", cart_products_path(@product), class: "btn btn-danger text-white"%>
            <% if user_signed_in?%>
              <% if current_user.id != @product.user_id %>
              <form action="/cart_products" method="POST" data-turbo="false">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <%= hidden_field_tag :product_id, @product.id %>
                <input type="submit" value="Add to cart", class= "btn btn-danger text-white">
              </form>
              <% end  %>
            <% else %>
              <%= link_to "Sign in to Add to Cart", new_user_session_path, class: "btn btn-primary" %>
            <% end %>
          </div>
      </div>
      <div>
            <%= link_to "Return to products", products_path %>
      </div>
    <hr class="my-2">

    <div class="row">
      <div class="col-12 col-sm-6">
        <h3>Reviews</h3>
        <% if @product.reviews.empty? %>
          <small><em class="text-muted">Be the first one to review this product</em></small>
        <% end %>
        <% @product.reviews.each do |review| %>
          <div>
            <%= review.rating.times do %>
              <i class="fas fa-star star-yellow"></i>
            <% end %>
            <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
            <p class="mb-0"><%= review.comment %></p>
          </div>
          <hr>
        <% end %>
      </div>
      <div class="col-12 col-sm-6">
        <div class="bg-white rounded p-3">
          <% if !current_user %>
              <h5>Add your review</h5>
              <%= simple_form_for [@product, @review] do |f| %>
                <%= f.input :comment, placeholder: "Add your review here..." %>
                <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { data: { controller: "star-rating" } } %>
                <%= f.submit class: "btn btn-primary mt-2" %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>